---

  - name: production
    hosts: production
    become: true
    gather_facts: true
    remote_user: ec2-user

    handlers: 
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    pre_tasks:
      - debug: msg="Target MAchine OS Family={{ansible_os_family}}"
      - debug: msg="Target Machine OS={{ ansible_distribution }} "
      - debug: msg="Target Machine OS Major Version={{ ansible_distribution_major_version }}"
      
      - name: set hostname
        hostname: name={{ hostname }}
      - name: set /etc/hosts
        lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1" line="127.0.0.1 {{ hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4"
    
    roles: 
    - { role: timezone }
    - { role: basikpkgs }

    tasks:
    - name: Set authorized key for dennis
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', 'dennis.pub') }}"
    
    - name: Java OpenJDK | Install 
      package: name={{ item }} state=present exclude=latest
      with_items:
        - java-{{ redhat_java_version }}-openjdk{{ java_patch }}
        - java-{{ redhat_java_version }}-openjdk-devel{{ java_patch }}

    - name: Configure prompt red in production machines
      template:
        src: promptcolor.sh.j2
        dest: /etc/profile.d/promptcolor.sh
        mode: 0644

    - name: Enable - httpd (Apache)
      systemd:
        name: httpd
        enabled: yes

    - name: httpd_started
      become: yes
      service:
        name: httpd
        state: started

  - name: test
    hosts: test
    become: true
    gather_facts: true
    remote_user: ec2-user
    tags: test

    handlers: 
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    pre_tasks:
      - debug: msg="Target MAchine OS Family={{ansible_os_family}}"
      - debug: msg="Target Machine OS={{ ansible_distribution }} "
      - debug: msg="Target Machine OS Major Version={{ ansible_distribution_major_version }}"
      
      - name: set hostname
        hostname: name={{ hostname }}
      - name: set /etc/hosts
        lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1" line="127.0.0.1 {{ hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4"

    roles: 
    - { role: timezone }
    - { role: basikpkgs }

    tasks:
    - name: Set authorized key for dennis
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', 'dennis.pub') }}"
          
    - name: Java OpenJDK | Install 
      package: name={{ item }} state=present exclude=latest
      with_items:
        - java-{{ redhat_java_version }}-openjdk{{ java_patch }}
        - java-{{ redhat_java_version }}-openjdk-devel{{ java_patch }}

    - name: Configure prompt red in production machines
      template:
        src: promptcolor.sh.j2
        dest: /etc/profile.d/promptcolor.sh
        mode: 0644

    - name: Enable - httpd (Apache)
      systemd:
        name: httpd
        enabled: yes

    - name: httpd_started
      become: yes
      service:
        name: httpd
        state: started
